# https://github.com/atom/ci
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: mkdir c:\temp
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off